// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package com.app;

public final class Bank {
  private Bank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccountDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.app.AccountDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 accountnumber = 1;</code>
     * @return The accountnumber.
     */
    int getAccountnumber();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>float balance = 3;</code>
     * @return The balance.
     */
    float getBalance();
  }
  /**
   * Protobuf type {@code com.app.AccountDetails}
   */
  public static final class AccountDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.app.AccountDetails)
      AccountDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountDetails.newBuilder() to construct.
    private AccountDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountDetails() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccountDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.Bank.internal_static_com_app_AccountDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.Bank.internal_static_com_app_AccountDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.Bank.AccountDetails.class, com.app.Bank.AccountDetails.Builder.class);
    }

    public static final int ACCOUNTNUMBER_FIELD_NUMBER = 1;
    private int accountnumber_ = 0;
    /**
     * <code>int32 accountnumber = 1;</code>
     * @return The accountnumber.
     */
    @java.lang.Override
    public int getAccountnumber() {
      return accountnumber_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BALANCE_FIELD_NUMBER = 3;
    private float balance_ = 0F;
    /**
     * <code>float balance = 3;</code>
     * @return The balance.
     */
    @java.lang.Override
    public float getBalance() {
      return balance_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (accountnumber_ != 0) {
        output.writeInt32(1, accountnumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (java.lang.Float.floatToRawIntBits(balance_) != 0) {
        output.writeFloat(3, balance_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (accountnumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, accountnumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (java.lang.Float.floatToRawIntBits(balance_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, balance_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.app.Bank.AccountDetails)) {
        return super.equals(obj);
      }
      com.app.Bank.AccountDetails other = (com.app.Bank.AccountDetails) obj;

      if (getAccountnumber()
          != other.getAccountnumber()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Float.floatToIntBits(getBalance())
          != java.lang.Float.floatToIntBits(
              other.getBalance())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getAccountnumber();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBalance());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.app.Bank.AccountDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.Bank.AccountDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.Bank.AccountDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.Bank.AccountDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.Bank.AccountDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.Bank.AccountDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.Bank.AccountDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.app.Bank.AccountDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.app.Bank.AccountDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.app.Bank.AccountDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.app.Bank.AccountDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.app.Bank.AccountDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.app.Bank.AccountDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.app.AccountDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.app.AccountDetails)
        com.app.Bank.AccountDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.Bank.internal_static_com_app_AccountDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.Bank.internal_static_com_app_AccountDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.Bank.AccountDetails.class, com.app.Bank.AccountDetails.Builder.class);
      }

      // Construct using com.app.Bank.AccountDetails.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        accountnumber_ = 0;
        name_ = "";
        balance_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.Bank.internal_static_com_app_AccountDetails_descriptor;
      }

      @java.lang.Override
      public com.app.Bank.AccountDetails getDefaultInstanceForType() {
        return com.app.Bank.AccountDetails.getDefaultInstance();
      }

      @java.lang.Override
      public com.app.Bank.AccountDetails build() {
        com.app.Bank.AccountDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.app.Bank.AccountDetails buildPartial() {
        com.app.Bank.AccountDetails result = new com.app.Bank.AccountDetails(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.app.Bank.AccountDetails result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.accountnumber_ = accountnumber_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.balance_ = balance_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.Bank.AccountDetails) {
          return mergeFrom((com.app.Bank.AccountDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.Bank.AccountDetails other) {
        if (other == com.app.Bank.AccountDetails.getDefaultInstance()) return this;
        if (other.getAccountnumber() != 0) {
          setAccountnumber(other.getAccountnumber());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getBalance() != 0F) {
          setBalance(other.getBalance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                accountnumber_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 29: {
                balance_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int accountnumber_ ;
      /**
       * <code>int32 accountnumber = 1;</code>
       * @return The accountnumber.
       */
      @java.lang.Override
      public int getAccountnumber() {
        return accountnumber_;
      }
      /**
       * <code>int32 accountnumber = 1;</code>
       * @param value The accountnumber to set.
       * @return This builder for chaining.
       */
      public Builder setAccountnumber(int value) {
        
        accountnumber_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 accountnumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountnumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountnumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private float balance_ ;
      /**
       * <code>float balance = 3;</code>
       * @return The balance.
       */
      @java.lang.Override
      public float getBalance() {
        return balance_;
      }
      /**
       * <code>float balance = 3;</code>
       * @param value The balance to set.
       * @return This builder for chaining.
       */
      public Builder setBalance(float value) {
        
        balance_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float balance = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBalance() {
        bitField0_ = (bitField0_ & ~0x00000004);
        balance_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.app.AccountDetails)
    }

    // @@protoc_insertion_point(class_scope:com.app.AccountDetails)
    private static final com.app.Bank.AccountDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.app.Bank.AccountDetails();
    }

    public static com.app.Bank.AccountDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountDetails>
        PARSER = new com.google.protobuf.AbstractParser<AccountDetails>() {
      @java.lang.Override
      public AccountDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AccountDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.app.Bank.AccountDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AccountMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.app.AccountMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    int getAccountsCount();
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    boolean containsAccounts(
        int key);
    /**
     * Use {@link #getAccountsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails>
    getAccounts();
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails>
    getAccountsMap();
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    /* nullable */
com.app.Bank.AccountDetails getAccountsOrDefault(
        int key,
        /* nullable */
com.app.Bank.AccountDetails defaultValue);
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    com.app.Bank.AccountDetails getAccountsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code com.app.AccountMap}
   */
  public static final class AccountMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.app.AccountMap)
      AccountMapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AccountMap.newBuilder() to construct.
    private AccountMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccountMap() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AccountMap();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.Bank.internal_static_com_app_AccountMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAccounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.Bank.internal_static_com_app_AccountMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.Bank.AccountMap.class, com.app.Bank.AccountMap.Builder.class);
    }

    public static final int ACCOUNTS_FIELD_NUMBER = 1;
    private static final class AccountsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.app.Bank.AccountDetails> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.app.Bank.AccountDetails>newDefaultInstance(
                  com.app.Bank.internal_static_com_app_AccountMap_AccountsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.app.Bank.AccountDetails.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, com.app.Bank.AccountDetails> accounts_;
    private com.google.protobuf.MapField<java.lang.Integer, com.app.Bank.AccountDetails>
    internalGetAccounts() {
      if (accounts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AccountsDefaultEntryHolder.defaultEntry);
      }
      return accounts_;
    }
    public int getAccountsCount() {
      return internalGetAccounts().getMap().size();
    }
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    @java.lang.Override
    public boolean containsAccounts(
        int key) {
      
      return internalGetAccounts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAccountsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> getAccounts() {
      return getAccountsMap();
    }
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> getAccountsMap() {
      return internalGetAccounts().getMap();
    }
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.app.Bank.AccountDetails getAccountsOrDefault(
        int key,
        /* nullable */
com.app.Bank.AccountDetails defaultValue) {
      
      java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> map =
          internalGetAccounts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
     */
    @java.lang.Override
    public com.app.Bank.AccountDetails getAccountsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> map =
          internalGetAccounts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetAccounts(),
          AccountsDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.app.Bank.AccountDetails> entry
           : internalGetAccounts().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.app.Bank.AccountDetails>
        accounts__ = AccountsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, accounts__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.app.Bank.AccountMap)) {
        return super.equals(obj);
      }
      com.app.Bank.AccountMap other = (com.app.Bank.AccountMap) obj;

      if (!internalGetAccounts().equals(
          other.internalGetAccounts())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetAccounts().getMap().isEmpty()) {
        hash = (37 * hash) + ACCOUNTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAccounts().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.app.Bank.AccountMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.Bank.AccountMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.Bank.AccountMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.Bank.AccountMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.Bank.AccountMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.Bank.AccountMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.Bank.AccountMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.app.Bank.AccountMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.app.Bank.AccountMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.app.Bank.AccountMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.app.Bank.AccountMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.app.Bank.AccountMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.app.Bank.AccountMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.app.AccountMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.app.AccountMap)
        com.app.Bank.AccountMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.Bank.internal_static_com_app_AccountMap_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetAccounts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableAccounts();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.Bank.internal_static_com_app_AccountMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.Bank.AccountMap.class, com.app.Bank.AccountMap.Builder.class);
      }

      // Construct using com.app.Bank.AccountMap.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableAccounts().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.Bank.internal_static_com_app_AccountMap_descriptor;
      }

      @java.lang.Override
      public com.app.Bank.AccountMap getDefaultInstanceForType() {
        return com.app.Bank.AccountMap.getDefaultInstance();
      }

      @java.lang.Override
      public com.app.Bank.AccountMap build() {
        com.app.Bank.AccountMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.app.Bank.AccountMap buildPartial() {
        com.app.Bank.AccountMap result = new com.app.Bank.AccountMap(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.app.Bank.AccountMap result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.accounts_ = internalGetAccounts();
          result.accounts_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.Bank.AccountMap) {
          return mergeFrom((com.app.Bank.AccountMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.Bank.AccountMap other) {
        if (other == com.app.Bank.AccountMap.getDefaultInstance()) return this;
        internalGetMutableAccounts().mergeFrom(
            other.internalGetAccounts());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.Integer, com.app.Bank.AccountDetails>
                accounts__ = input.readMessage(
                    AccountsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableAccounts().getMutableMap().put(
                    accounts__.getKey(), accounts__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, com.app.Bank.AccountDetails> accounts_;
      private com.google.protobuf.MapField<java.lang.Integer, com.app.Bank.AccountDetails>
          internalGetAccounts() {
        if (accounts_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AccountsDefaultEntryHolder.defaultEntry);
        }
        return accounts_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.app.Bank.AccountDetails>
          internalGetMutableAccounts() {
        if (accounts_ == null) {
          accounts_ = com.google.protobuf.MapField.newMapField(
              AccountsDefaultEntryHolder.defaultEntry);
        }
        if (!accounts_.isMutable()) {
          accounts_ = accounts_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return accounts_;
      }
      public int getAccountsCount() {
        return internalGetAccounts().getMap().size();
      }
      /**
       * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
       */
      @java.lang.Override
      public boolean containsAccounts(
          int key) {
        
        return internalGetAccounts().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAccountsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> getAccounts() {
        return getAccountsMap();
      }
      /**
       * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> getAccountsMap() {
        return internalGetAccounts().getMap();
      }
      /**
       * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.app.Bank.AccountDetails getAccountsOrDefault(
          int key,
          /* nullable */
com.app.Bank.AccountDetails defaultValue) {
        
        java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> map =
            internalGetAccounts().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
       */
      @java.lang.Override
      public com.app.Bank.AccountDetails getAccountsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> map =
            internalGetAccounts().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearAccounts() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableAccounts().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
       */
      public Builder removeAccounts(
          int key) {
        
        internalGetMutableAccounts().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails>
          getMutableAccounts() {
        bitField0_ |= 0x00000001;
        return internalGetMutableAccounts().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
       */
      public Builder putAccounts(
          int key,
          com.app.Bank.AccountDetails value) {
        
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableAccounts().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;int32, .com.app.AccountDetails&gt; accounts = 1;</code>
       */
      public Builder putAllAccounts(
          java.util.Map<java.lang.Integer, com.app.Bank.AccountDetails> values) {
        internalGetMutableAccounts().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.app.AccountMap)
    }

    // @@protoc_insertion_point(class_scope:com.app.AccountMap)
    private static final com.app.Bank.AccountMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.app.Bank.AccountMap();
    }

    public static com.app.Bank.AccountMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccountMap>
        PARSER = new com.google.protobuf.AbstractParser<AccountMap>() {
      @java.lang.Override
      public AccountMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AccountMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountMap> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.app.Bank.AccountMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_AccountDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_AccountDetails_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_AccountMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_AccountMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_AccountMap_AccountsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_AccountMap_AccountsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbank.proto\022\007com.app\"F\n\016AccountDetails\022" +
      "\025\n\raccountnumber\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\017\n\007" +
      "balance\030\003 \001(\002\"\213\001\n\nAccountMap\0223\n\010accounts" +
      "\030\001 \003(\0132!.com.app.AccountMap.AccountsEntr" +
      "y\032H\n\rAccountsEntry\022\013\n\003key\030\001 \001(\005\022&\n\005value" +
      "\030\002 \001(\0132\027.com.app.AccountDetails:\0028\001B\t\n\007c" +
      "om.appb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_app_AccountDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_app_AccountDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_AccountDetails_descriptor,
        new java.lang.String[] { "Accountnumber", "Name", "Balance", });
    internal_static_com_app_AccountMap_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_app_AccountMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_AccountMap_descriptor,
        new java.lang.String[] { "Accounts", });
    internal_static_com_app_AccountMap_AccountsEntry_descriptor =
      internal_static_com_app_AccountMap_descriptor.getNestedTypes().get(0);
    internal_static_com_app_AccountMap_AccountsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_AccountMap_AccountsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
